Section "Device"
        Identifier  "Freedreno Graphics"
        Driver      "modesetting"
        Option      "atomic" "true"
        Option      "TearFree" "true"
        Option      "TrippleBuffer" "true"
EndSection
